language: java
install: ./gradlew assemble -x :endpoints-management-control-appengine-all:assemble -x :endpoints-management-control-all:assemble
script: ./gradlew check -x :endpoints-management-control-appengine-all:check -x :endpoints-management-control-all:check
after_success:
  - ./gradlew jacocoTestReport
  - bash <(curl -s https://codecov.io/bash)
