/*
 * Copyright 2016 Google Inc. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.api.config;

import com.google.api.Service;
import com.google.api.Service.Builder;
import com.google.api.client.http.GenericUrl;
import com.google.api.client.http.HttpHeaders;
import com.google.api.client.http.HttpRequest;
import com.google.api.client.http.HttpResponse;
import com.google.api.client.http.HttpStatusCodes;
import com.google.api.client.http.HttpTransport;
import com.google.api.client.http.javanet.NetHttpTransport;
import com.google.appengine.api.appidentity.AppIdentityService;
import com.google.appengine.api.appidentity.AppIdentityService.GetAccessTokenResult;
import com.google.appengine.api.appidentity.AppIdentityServiceFactory;
import com.google.common.annotations.VisibleForTesting;
import com.google.common.base.Joiner;
import com.google.common.base.Preconditions;
import com.google.common.base.Strings;
import com.google.common.collect.ImmutableList;
import com.google.protobuf.util.JsonFormat;

import java.io.IOException;
import java.text.MessageFormat;
import java.util.List;

/**
 * Fetches service configuration from Google Service Management APIs.
 */
public final class ServiceConfigFetcher {
  private static final String SERVICE_NAME_KEY = "SERVICE_NAME";
  private static final String SERVICE_VERSION_KEY = "SERVICE_VERSION";

  private static final List<String> SCOPES =
      ImmutableList.of("https://www.googleapis.com/auth/cloud-platform");

  private static final String FIELD_MASKS = Joiner.on(',').join(
      "authentication",
      "http",
      "id",
      "logging",
      "logs",
      "metrics",
      "monitored_resources",
      "monitoring",
      "name",
      "producer_project_id",
      "system_parameters",
      "usage");

  private static final String SERVICE_MGMT_URL_TEMPLATE =
      "https://servicemanagement.googleapis.com/v1/services/{0}/config?configId={1}"
      + "&$fields=" + FIELD_MASKS;

  private final AppIdentityService appIdentityService;
  private final Environment environment;
  private final HttpTransport httpTransport;

  @VisibleForTesting
  ServiceConfigFetcher(
      AppIdentityService appIdentityService,
      Environment environment,
      HttpTransport httpTransport) {
    this.appIdentityService = appIdentityService;
    this.environment = environment;
    this.httpTransport = httpTransport;
  }

  /**
   * Fetches the service configuration using the service name and the service
   * version read from the environment variables.
   *
   * @return a {@link Service} object generated by the JSON response from Google
   * Service Management.
   */
  public Service fetch() {
    String serviceName = this.retrieveEnvironmentVarialbe(SERVICE_NAME_KEY);
    String serviceVersion = this.retrieveEnvironmentVarialbe(SERVICE_VERSION_KEY);

    return fetch(serviceName, serviceVersion);
  }

  /**
   * Fetches the service configuration with the given service name and service
   * version.
   *
   * @return a {@link Service} object generated by the JSON response from Google
   * Service Management.
   */
  public Service fetch(String serviceName, String serviceVersion) {
    Preconditions.checkArgument(!Strings.isNullOrEmpty(serviceName), "service name must be specified");
    Preconditions.checkArgument(!Strings.isNullOrEmpty(serviceVersion), "service version must be specified");

    HttpHeaders httpHeaders = new HttpHeaders();
    httpHeaders.setAuthorization("Bearer " + getAccessToken());

    String url = MessageFormat.format(SERVICE_MGMT_URL_TEMPLATE, serviceName, serviceVersion);
    final HttpResponse httpResponse;
    try {
      HttpRequest httpRequest = this.httpTransport.createRequestFactory()
          .buildGetRequest(new GenericUrl(url))
          .setThrowExceptionOnExecuteError(false)
          .setHeaders(httpHeaders);
      httpResponse = httpRequest.execute();
    } catch (IOException exception) {
      throw new ServiceConfigException(exception);
    }

    int statusCode = httpResponse.getStatusCode();
    if (statusCode != HttpStatusCodes.STATUS_CODE_OK) {
      String message = MessageFormat.format(
          "Failed to fetch service config (status code {0})",
          statusCode);
      throw new ServiceConfigException(message);
    }

    Service service = parseHttpResponse(httpResponse);
    validateServiceConfig(service, serviceName, serviceVersion);

    return service;
  }

  private String getAccessToken() {
    // TODO (yangguan): use Application Default Credentials to retrieve access
    // token instead of App Identity APIs.
    GetAccessTokenResult accessTokenResult =
        this.appIdentityService.getAccessToken(SCOPES);
    return accessTokenResult.getAccessToken();
  }

  private String retrieveEnvironmentVarialbe(String variableName) {
    String value = this.environment.getVariable(variableName);
    if (Strings.isNullOrEmpty(value)) {
      String errorMessage =
          String.format("Environment variable '%s' is not set", variableName);
      throw new IllegalArgumentException(errorMessage);
    }
    return value;
  }

  private static Service parseHttpResponse(HttpResponse httpResponse) {
    try {
      Builder builder = Service.newBuilder();
      JsonFormat.parser().merge(httpResponse.parseAsString(), builder);
      return builder.build();
    } catch (IOException exception) {
      throw new ServiceConfigException(
          "Failed to parse the HTTP response as service configuration",
          exception);
    }
  }

  private static void validateServiceConfig(
      Service service,
      String expectedServiceName,
      String expectedServiceVersion) {
    String serviceName = service.getName();
    if (!expectedServiceName.equals(serviceName)) {
      throw new ServiceConfigException("Unexpected service name in service config: " + serviceName);
    }

    String serviceVersion = service.getId();
    if (!expectedServiceVersion.equals(serviceVersion)) {
      throw new ServiceConfigException("Unexpected service version in service config: " + serviceVersion);
    }
  }

  /**
   * Create a {@link ServiceConfigFetcher} instance.
   */
  public static ServiceConfigFetcher create() {
    return new ServiceConfigFetcher(
        AppIdentityServiceFactory.getAppIdentityService(),
        new SystemEnvironment(),
        new NetHttpTransport());
  }

  private static final class SystemEnvironment implements Environment {
    @Override
    public String getVariable(String variableName) {
      return System.getenv(variableName);
    }
  }
}
