/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */

package com.google.api.services.servicecontrol.v1.model;

/**
 * AreaUnderCurveParams groups the metrics relevant to generating duration based metric from base
 * (snapshot) metric and delta (change) metric.  The generated metric has two dimensions:
 * resource usage metric and the duration the metric applies.
 *
 * Essentially the generated metric is the Area Under Curve(AUC) of the "duration - resource" usage
 * curve. This AUC metric is readily appliable to billing since "billable resource usage" depends on
 * resource usage and duration of the resource used.
 *
 * A service config may contain multiple resources and corresponding metrics. AreaUnderCurveParams
 * groups the relevant ones: which snapshot_metric and change_metric are used to produce which
 * generated_metric.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Google Service Control API. For a detailed
 * explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class AreaUnderCurveParams extends com.google.api.client.json.GenericJson {

  /**
   * Change of resource usage at a particular timestamp. This should a DELTA metric.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String changeMetric;

  /**
   * Metric generated from snapshot_metric and change_metric. This is also a DELTA metric.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String generatedMetric;

  /**
   * Total usage of a resource at a particular timestamp. This should be a GAUGE metric.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String snapshotMetric;

  /**
   * Change of resource usage at a particular timestamp. This should a DELTA metric.
   * @return value or {@code null} for none
   */
  public java.lang.String getChangeMetric() {
    return changeMetric;
  }

  /**
   * Change of resource usage at a particular timestamp. This should a DELTA metric.
   * @param changeMetric changeMetric or {@code null} for none
   */
  public AreaUnderCurveParams setChangeMetric(java.lang.String changeMetric) {
    this.changeMetric = changeMetric;
    return this;
  }

  /**
   * Metric generated from snapshot_metric and change_metric. This is also a DELTA metric.
   * @return value or {@code null} for none
   */
  public java.lang.String getGeneratedMetric() {
    return generatedMetric;
  }

  /**
   * Metric generated from snapshot_metric and change_metric. This is also a DELTA metric.
   * @param generatedMetric generatedMetric or {@code null} for none
   */
  public AreaUnderCurveParams setGeneratedMetric(java.lang.String generatedMetric) {
    this.generatedMetric = generatedMetric;
    return this;
  }

  /**
   * Total usage of a resource at a particular timestamp. This should be a GAUGE metric.
   * @return value or {@code null} for none
   */
  public java.lang.String getSnapshotMetric() {
    return snapshotMetric;
  }

  /**
   * Total usage of a resource at a particular timestamp. This should be a GAUGE metric.
   * @param snapshotMetric snapshotMetric or {@code null} for none
   */
  public AreaUnderCurveParams setSnapshotMetric(java.lang.String snapshotMetric) {
    this.snapshotMetric = snapshotMetric;
    return this;
  }

  @Override
  public AreaUnderCurveParams set(String fieldName, Object value) {
    return (AreaUnderCurveParams) super.set(fieldName, value);
  }

  @Override
  public AreaUnderCurveParams clone() {
    return (AreaUnderCurveParams) super.clone();
  }

}
