/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */

package com.google.api.services.servicecontrol.v1.model;

/**
 * Defines the billing status requirements for operations.
 *
 * When used with [Service Control API](https://cloud.google.com/service-control/), the following
 * statuses are supported:
 *
 * - **current**: the associated billing account is up to date and capable of                paying
 * for resource usages. - **delinquent**: the associated billing account has a correctable problem,
 * such as late payment.
 *
 * Mostly services should only allow `current` status when serving requests. In addition, services
 * can choose to allow both `current` and `delinquent` statuses when serving read-only requests to
 * resources. If the list of allowed_statuses is empty, it means no billing requirement.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Google Service Control API. For a detailed
 * explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class BillingStatusRule extends com.google.api.client.json.GenericJson {

  /**
   * Allowed billing statuses. The billing status check passes if the actual billing status matches
   * any of the provided values here.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> allowedStatuses;

  /**
   * Selects the operation names to which this rule applies. Refer to selector for syntax details.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String selector;

  /**
   * Allowed billing statuses. The billing status check passes if the actual billing status matches
   * any of the provided values here.
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getAllowedStatuses() {
    return allowedStatuses;
  }

  /**
   * Allowed billing statuses. The billing status check passes if the actual billing status matches
   * any of the provided values here.
   * @param allowedStatuses allowedStatuses or {@code null} for none
   */
  public BillingStatusRule setAllowedStatuses(java.util.List<java.lang.String> allowedStatuses) {
    this.allowedStatuses = allowedStatuses;
    return this;
  }

  /**
   * Selects the operation names to which this rule applies. Refer to selector for syntax details.
   * @return value or {@code null} for none
   */
  public java.lang.String getSelector() {
    return selector;
  }

  /**
   * Selects the operation names to which this rule applies. Refer to selector for syntax details.
   * @param selector selector or {@code null} for none
   */
  public BillingStatusRule setSelector(java.lang.String selector) {
    this.selector = selector;
    return this;
  }

  @Override
  public BillingStatusRule set(String fieldName, Object value) {
    return (BillingStatusRule) super.set(fieldName, value);
  }

  @Override
  public BillingStatusRule clone() {
    return (BillingStatusRule) super.clone();
  }

}
