/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */

package com.google.api.services.servicecontrol.v1.model;

/**
 * The response message of the Check method.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Google Service Control API. For a detailed
 * explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class CheckResponse extends com.google.api.client.json.GenericJson {

  /**
   * Indicate the decision of the check.
   *
   * If no check errors are present, the service should process the operation. Otherwise the service
   * should use the list of errors to determine the appropriate action.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<CheckError> checkErrors;

  /**
   * The same operation_id value used in the CheckRequest. Used for logging and diagnostics purpose.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String operationId;

  /**
   * Indicate the decision of the check.
   *
   * If no check errors are present, the service should process the operation. Otherwise the service
   * should use the list of errors to determine the appropriate action.
   * @return value or {@code null} for none
   */
  public java.util.List<CheckError> getCheckErrors() {
    return checkErrors;
  }

  /**
   * Indicate the decision of the check.
   *
   * If no check errors are present, the service should process the operation. Otherwise the service
   * should use the list of errors to determine the appropriate action.
   * @param checkErrors checkErrors or {@code null} for none
   */
  public CheckResponse setCheckErrors(java.util.List<CheckError> checkErrors) {
    this.checkErrors = checkErrors;
    return this;
  }

  /**
   * The same operation_id value used in the CheckRequest. Used for logging and diagnostics purpose.
   * @return value or {@code null} for none
   */
  public java.lang.String getOperationId() {
    return operationId;
  }

  /**
   * The same operation_id value used in the CheckRequest. Used for logging and diagnostics purpose.
   * @param operationId operationId or {@code null} for none
   */
  public CheckResponse setOperationId(java.lang.String operationId) {
    this.operationId = operationId;
    return this;
  }

  @Override
  public CheckResponse set(String fieldName, Object value) {
    return (CheckResponse) super.set(fieldName, value);
  }

  @Override
  public CheckResponse clone() {
    return (CheckResponse) super.clone();
  }

}
