/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */

package com.google.api.services.servicecontrol.v1.model;

/**
 * Defines the errors to be returned in google.api.servicecontrol.v1.CheckResponse.check_errors.
 * NOTE: The list of error code must be in sync with the list in
 * http://cs/google3/tech/internal/env/framework/wrappers/chemist/chemist_wrapper.cc=525
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Google Service Control API. For a detailed
 * explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class CheckError extends com.google.api.client.json.GenericJson {

  /**
   * The error code.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String code;

  /**
   * The error detail.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String detail;

  /**
   * The error code.
   * @return value or {@code null} for none
   */
  public java.lang.String getCode() {
    return code;
  }

  /**
   * The error code.
   * @param code code or {@code null} for none
   */
  public CheckError setCode(java.lang.String code) {
    this.code = code;
    return this;
  }

  /**
   * The error detail.
   * @return value or {@code null} for none
   */
  public java.lang.String getDetail() {
    return detail;
  }

  /**
   * The error detail.
   * @param detail detail or {@code null} for none
   */
  public CheckError setDetail(java.lang.String detail) {
    this.detail = detail;
    return this;
  }

  @Override
  public CheckError set(String fieldName, Object value) {
    return (CheckError) super.set(fieldName, value);
  }

  @Override
  public CheckError clone() {
    return (CheckError) super.clone();
  }

}
