/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */

package com.google.api.services.servicecontrol.v1.model;

/**
 * Defines the HTTP configuration for a service. It contains a list of HttpRule, each specifying the
 * mapping of an RPC method to one or more HTTP REST API methods.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Google Service Control API. For a detailed
 * explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Http extends com.google.api.client.json.GenericJson {

  /**
   * A list of HTTP rules for configuring the HTTP REST API methods.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<HttpRule> rules;

  static {
    // hack to force ProGuard to consider HttpRule used, since otherwise it would be stripped out
    // see https://github.com/google/google-api-java-client/issues/543
    com.google.api.client.util.Data.nullOf(HttpRule.class);
  }

  /**
   * A list of HTTP rules for configuring the HTTP REST API methods.
   * @return value or {@code null} for none
   */
  public java.util.List<HttpRule> getRules() {
    return rules;
  }

  /**
   * A list of HTTP rules for configuring the HTTP REST API methods.
   * @param rules rules or {@code null} for none
   */
  public Http setRules(java.util.List<HttpRule> rules) {
    this.rules = rules;
    return this;
  }

  @Override
  public Http set(String fieldName, Object value) {
    return (Http) super.set(fieldName, value);
  }

  @Override
  public Http clone() {
    return (Http) super.clone();
  }

}
