/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */

package com.google.api.services.servicecontrol.v1.model;

/**
 * A protocol buffer option, which can be attached to a message, field, enumeration, etc.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Google Service Control API. For a detailed
 * explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Option extends com.google.api.client.json.GenericJson {

  /**
   * The option's name. For example, `"java_package"`.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * The option's value. For example, `"com.google.protobuf"`.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.Map<String, java.lang.Object> value;

  /**
   * The option's name. For example, `"java_package"`.
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * The option's name. For example, `"java_package"`.
   * @param name name or {@code null} for none
   */
  public Option setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * The option's value. For example, `"com.google.protobuf"`.
   * @return value or {@code null} for none
   */
  public java.util.Map<String, java.lang.Object> getValue() {
    return value;
  }

  /**
   * The option's value. For example, `"com.google.protobuf"`.
   * @param value value or {@code null} for none
   */
  public Option setValue(java.util.Map<String, java.lang.Object> value) {
    this.value = value;
    return this;
  }

  @Override
  public Option set(String fieldName, Object value) {
    return (Option) super.set(fieldName, value);
  }

  @Override
  public Option clone() {
    return (Option) super.clone();
  }

}
