/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */

package com.google.api.services.servicecontrol.v1.model;

/**
 * A descriptor for defining project properties for a service. One service may have many consumer
 * projects, and the service may want to behave differently depending on some properties on the
 * project. For example, a project may be associated with a school, or a business, or a government
 * agency, a business type property on the project may affect how a service responds to the client.
 * This descriptor defines which properties are allowed to be set on a project.
 *
 * Example:
 *
 *    project_properties:      properties:      - name: NO_WATERMARK        type: BOOL
 * description: Allows usage of the API without watermarks.      - name: EXTENDED_TILE_CACHE_PERIOD
 * type: INT64
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Google Service Control API. For a detailed
 * explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ProjectProperties extends com.google.api.client.json.GenericJson {

  /**
   * List of per consumer project-specific properties.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<Property> properties;

  /**
   * List of per consumer project-specific properties.
   * @return value or {@code null} for none
   */
  public java.util.List<Property> getProperties() {
    return properties;
  }

  /**
   * List of per consumer project-specific properties.
   * @param properties properties or {@code null} for none
   */
  public ProjectProperties setProperties(java.util.List<Property> properties) {
    this.properties = properties;
    return this;
  }

  @Override
  public ProjectProperties set(String fieldName, Object value) {
    return (ProjectProperties) super.set(fieldName, value);
  }

  @Override
  public ProjectProperties clone() {
    return (ProjectProperties) super.clone();
  }

}
