/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */

package com.google.api.services.servicecontrol.v1.model;

/**
 * A quota group mapping.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Google Service Control API. For a detailed
 * explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class QuotaGroupMapping extends com.google.api.client.json.GenericJson {

  /**
   * Number of tokens to consume for each request. This allows different cost to be associated with
   * different methods that consume from the same quota group. By default, each request will cost
   * one token.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer cost;

  /**
   * The `QuotaGroup.name` of the group. Requests for the mapped methods will consume tokens from
   * each of the limits defined in this group.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String group;

  /**
   * Number of tokens to consume for each request. This allows different cost to be associated with
   * different methods that consume from the same quota group. By default, each request will cost
   * one token.
   * @return value or {@code null} for none
   */
  public java.lang.Integer getCost() {
    return cost;
  }

  /**
   * Number of tokens to consume for each request. This allows different cost to be associated with
   * different methods that consume from the same quota group. By default, each request will cost
   * one token.
   * @param cost cost or {@code null} for none
   */
  public QuotaGroupMapping setCost(java.lang.Integer cost) {
    this.cost = cost;
    return this;
  }

  /**
   * The `QuotaGroup.name` of the group. Requests for the mapped methods will consume tokens from
   * each of the limits defined in this group.
   * @return value or {@code null} for none
   */
  public java.lang.String getGroup() {
    return group;
  }

  /**
   * The `QuotaGroup.name` of the group. Requests for the mapped methods will consume tokens from
   * each of the limits defined in this group.
   * @param group group or {@code null} for none
   */
  public QuotaGroupMapping setGroup(java.lang.String group) {
    this.group = group;
    return this;
  }

  @Override
  public QuotaGroupMapping set(String fieldName, Object value) {
    return (QuotaGroupMapping) super.set(fieldName, value);
  }

  @Override
  public QuotaGroupMapping clone() {
    return (QuotaGroupMapping) super.clone();
  }

}
