/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */

package com.google.api.services.servicecontrol.v1.model;

/**
 * `QuotaRule` maps a method to a set of `QuotaGroup`s.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Google Service Control API. For a detailed
 * explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class QuotaRule extends com.google.api.client.json.GenericJson {

  /**
   * Indicates if quota checking should be enforced. Quota will be disabled for methods without
   * quota rules or with quota rules having this field set to true. When this field is set to true,
   * no quota group mapping is allowed.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean disableQuota;

  /**
   * Quota groups to be used for this method. This supports associating a cost with each quota
   * group.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<QuotaGroupMapping> groups;

  /**
   * Selects methods to which this rule applies.
   *
   * Refer to selector for syntax details.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String selector;

  /**
   * Indicates if quota checking should be enforced. Quota will be disabled for methods without
   * quota rules or with quota rules having this field set to true. When this field is set to true,
   * no quota group mapping is allowed.
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getDisableQuota() {
    return disableQuota;
  }

  /**
   * Indicates if quota checking should be enforced. Quota will be disabled for methods without
   * quota rules or with quota rules having this field set to true. When this field is set to true,
   * no quota group mapping is allowed.
   * @param disableQuota disableQuota or {@code null} for none
   */
  public QuotaRule setDisableQuota(java.lang.Boolean disableQuota) {
    this.disableQuota = disableQuota;
    return this;
  }

  /**
   * Quota groups to be used for this method. This supports associating a cost with each quota
   * group.
   * @return value or {@code null} for none
   */
  public java.util.List<QuotaGroupMapping> getGroups() {
    return groups;
  }

  /**
   * Quota groups to be used for this method. This supports associating a cost with each quota
   * group.
   * @param groups groups or {@code null} for none
   */
  public QuotaRule setGroups(java.util.List<QuotaGroupMapping> groups) {
    this.groups = groups;
    return this;
  }

  /**
   * Selects methods to which this rule applies.
   *
   * Refer to selector for syntax details.
   * @return value or {@code null} for none
   */
  public java.lang.String getSelector() {
    return selector;
  }

  /**
   * Selects methods to which this rule applies.
   *
   * Refer to selector for syntax details.
   * @param selector selector or {@code null} for none
   */
  public QuotaRule setSelector(java.lang.String selector) {
    this.selector = selector;
    return this;
  }

  @Override
  public QuotaRule set(String fieldName, Object value) {
    return (QuotaRule) super.set(fieldName, value);
  }

  @Override
  public QuotaRule clone() {
    return (QuotaRule) super.clone();
  }

}
